/*
 * generated by Xtext 2.26.0
 */
package dev.faurskov.eas;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
